installdistribution:
  name: almalinux
  version: 9

root_authorized_keys:
  - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOm4c78woS/1JU/A+jeAuKjuThZSH7qUbzuS+ldogq2v geert@clt-mgt05'

strict_selinux: true # Touches /.autorelabel

continue_install: false # When true, then it needs current kernel version == installed kernel version. This is forced by tuxifier.

rootpw: rootpw
installdisk:
  disks:
    - device: /dev/vda
      label: gpt
      partitions:
        - id: bios_grub
          number: 1
          part_start: 1MiB
          part_end: 2MiB
          flags:
            - bios_grub
        - id: boot
          number: 2
          part_start: 2MiB
          part_end: 1024MiB
          fstype: ext3
          mkfs_opts: "-L boot -O ^orphan_file"
          mountpoint: /boot
          mount_opts: defaults
          mount_order: 20

        - id: pv.01
          number: 3
          part_start: 2GiB
          part_end: 100%
          flags:
            - lvm

  lvm_layout:
    - vg: vg.rh
      pvs:
        - pv.01
      lvs:
        - lv: swap
          size: 512M
          fstype: swap
          mkfs_opts: "-L swap"

        - lv: root
          size: 100%FREE
          fstype: ext4
          mkfs_opts: "-L root -O ^orphan_file"
          mountpoint: /
          mount_opts: defaults
          mount_order: 10
